[package]
name = "meilisearch-http"
description = "MeiliSearch HTTP server"
version = "0.19.0"
license = "MIT"
authors = [
    "Quentin de Quelen <quentin@dequelen.me>",
    "Clément Renault <clement@meilisearch.com>",
]
edition = "2018"

[[bin]]
name = "meilisearch"
path = "src/main.rs"

[features]
default = ["sentry"]

[dependencies]
actix-cors = "0.5.4"
actix-http = "2.2.0"
actix-rt = "1.1.1"
actix-service = "1.0.6"
actix-web = { version = "3.3.2", features = ["rustls"] }
bytes = "1.0.0"
chrono = { version = "0.4.19", features = ["serde"] }
crossbeam-channel = "0.5.0"
env_logger = "0.8.2"
flate2 = "1.0.19"
futures = "0.3.8"
http = "0.2.2"
indexmap = { version = "1.6.1", features = ["serde-1"] }
log = "0.4.11"
main_error = "0.1.1"
meilisearch-core = { path = "../meilisearch-core", version = "0.19.0" }
meilisearch-error = { path = "../meilisearch-error", version = "0.19.0" }
meilisearch-schema = { path = "../meilisearch-schema", version = "0.19.0" }
mime = "0.3.16"
once_cell = "1.5.2"
rand = "0.8.1"
regex = "1.4.2"
rustls = "0.18.0"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = { version = "1.0.61", features = ["preserve_order"] }
serde_qs = "0.8.2"
sha2 = "0.9.2"
siphasher = "0.3.3"
slice-group-by = "0.2.6"
structopt = "0.3.21"
tar = "0.4.30"
tempfile = "3.1.0"
tokio = { version = "0.2", features = ["macros"] }
ureq = { version = "2.0.0", features = ["tls"], default-features = false }
uuid = "0.8"
walkdir = "2.3.1"
whoami = "1.0.3"

[dependencies.sentry]
version = "0.18.1"
default-features = false
features = [
    "with_client_implementation",
    "with_panic",
    "with_failure",
    "with_device_info",
    "with_rust_info",
    "with_reqwest_transport",
    "with_rustls",
    "with_env_logger"
]
optional = true

[dev-dependencies]
serde_url_params = "0.2.0"
tempdir = "0.3.7"
tokio = { version = "0.2", features = ["macros", "time"] }

[dev-dependencies.assert-json-diff]
git = "https://github.com/qdequele/assert-json-diff"
branch = "master"

[build-dependencies]
vergen = "3.1.0"

[target.'cfg(unix)'.dependencies]
jemallocator = "0.3.2"
